package com.halo.decomp;

/** Player-facing paths verified against the bundled OpenCE menu XML/callbacks. */
final class InGameNetworkGuide {
    private InGameNetworkGuide() {}

    static final String BROWSE =
        "START HERE\n"
        + "Press Play in the launcher. In the game's main menu, open Multiplayer. "
        + "Create or choose a player profile if asked. Browsing, joining and hosting now happen inside the game.\n\n"
        + "PUBLIC GAMES\n"
        + "1. Multiplayer > Join Game > Server Browser.\n"
        + "2. Use REFRESH to request current listings. The list includes PvP and campaign co-op, "
        + "with the most populated games first. The list auto-scrolls as you move through rows; "
        + "use the stick/D-pad on controllers or MOVE on Android to see more.\n"
        + "3. Select a server row or JOIN GAME. Locked games ask for the host's password. "
        + "If an in-progress lobby preview opens, select JOIN GAME there too.\n\n"
        + "If the in-game list is empty, return to the launcher and use Browse multiplayer servers or "
        + "Browse campaign co-op servers. The community directory shows reported population by network version; "
        + "select a target from 11 through 24 or All compatible networks for the next launch. This changes native discovery and join admission. "
        + "Targets 11–22 support original Xbox-map PvP; co-op and Custom Edition require 23 or 24. Hosting stays on network 24.\n\n"
        + "FILTERS\n"
        + "Use FILTERS > GAME TYPE > CO-OP for campaign games, or ANY for all game types. "
        + "You can include empty/full servers, filter team games or passwords, and select ALL MAPS or KNOWN MAPS. "
        + "Choose APPLY to save; DEFAULTS followed by APPLY restores the default filters. "
        + "Known Maps checks the local catalog, not file fingerprints or disc revision. "
        + "Ping is unavailable before connection.\n\n"
        + "LOCAL NETWORK\n"
        + "Use Multiplayer > Join Game > LAN on devices on the same reachable network. "
        + "Use REFRESH, select the host and JOIN GAME. Guest Wi-Fi/client isolation can prevent discovery.\n\n"
        + "MENU INPUT\n"
        + "Quest: point with your weapon hand and pull the trigger, or use stick navigation and A; B goes back. "
        + "Android: tap menu items in free screen space, or use MOVE and the circular A/B controls. "
        + "Gamepad: D-pad/stick to navigate, A to select, B to go back. Use left/right on option arrows. "
        + "Selecting an editable name, password or invite opens the in-game keyboard; finish with its accept control.";

    static final String HOST_PVP =
        "HOST MULTIPLAYER\n"
        + "1. Press Play, then Multiplayer > Create Game > Internet for remote players, or LAN for your local network.\n"
        + "2. On the map screen, select MULTIPLAYER (or CUSTOM MULTIPLAYER for supported installed custom maps), "
        + "choose the map, then choose a gametype. Everyone needs compatible map files.\n"
        + "3. In Server Setup, set GAME NAME and MAXIMUM PLAYERS. Review GAME TYPE, PLAYER OPTIONS, "
        + "ITEM OPTIONS, VEHICLE OPTIONS, INDICATOR OPTIONS and TEAMPLAY OPTIONS. "
        + "These configure this game; Multiplayer > Edit Gametypes manages saved gametypes.\n"
        + "4. For an Internet game, LISTING: PUBLIC advertises it in Server Browser. "
        + "PRIVATE is invite-only. A public game can have a PASSWORD.\n"
        + "5. Select START GAME to enter the lobby. Use START NOW when ready; the lobby also has its normal countdown. "
        + "Keep the host running while others join. Internet hosting copies an invite link to the device clipboard "
        + "when it becomes available; share that with friends for Direct Link.\n\n"
        + "If Internet/listing controls are unavailable, check Settings > Network Setup > INTERNET PLAY "
        + "and the launcher Network settings. Public listing also requires public-lobby access to be enabled. "
        + "A visible listing does not guarantee that your router, mobile carrier or VPN allows game traffic.";

    static final String COOP =
        "HOST ONLINE CAMPAIGN CO-OP\n"
        + "1. Press Play, then Multiplayer > Create Game > Internet (or LAN for local-network play).\n"
        + "2. Change the map category to SINGLEPLAYER, choose the mission, then choose difficulty. "
        + "CUSTOM SINGLEPLAYER is for supported installed custom campaign maps; listing one does not guarantee mod compatibility.\n"
        + "3. Server Setup contains GAME NAME, MAXIMUM PLAYERS, FRIENDLY FIRE, EXTRA ENEMIES and PLAYER COLLISIONS. "
        + "Extra Enemies can scale squads per additional player or by a fixed multiplier. "
        + "Its amount row changes with the chosen mode.\n"
        + "4. Choose PUBLIC to appear in Server Browser, or PRIVATE and share the invite. "
        + "Optionally set a password for a public game.\n"
        + "5. Select START GAME, then START NOW in the lobby when ready. Players may also join a mission already in progress.\n\n"
        + "JOIN CAMPAIGN CO-OP\n"
        + "Multiplayer > Join Game > Server Browser > FILTERS: GAME TYPE = CO-OP > APPLY. "
        + "Choose the host and JOIN GAME. For a private invite, use Join Game > Direct Link; "
        + "for nearby hosts, use Join Game > LAN.\n\n"
        + "PLAYER LIMITS\n"
        + "Server Setup offers 2 to 128 players. High counts and extra enemies increase CPU, memory and network load; "
        + "128 is a capacity option, not a performance guarantee on Quest or phones. Start with a small group. "
        + "Everyone needs the same network version and compatible campaign/resource files.\n\n"
        + "LOCAL SPLIT SCREEN IS DIFFERENT\n"
        + "The separate Multiplayer > CO-OP CAMPAIGN entry is local split screen, not online hosting. "
        + "It and ADD PLAYER do not provide separate headset views and are blocked on Quest. "
        + "Use Create Game > Internet/LAN > SINGLEPLAYER for co-op between devices. "
        + "Flat Android retains local split-screen paths with separate controllers; device validation is still needed.";

    static final String INVITES =
        "DIRECT LINK\n"
        + "1. Ask the host for their current halo://join/... invite (or its 64-digit code). "
        + "Invites from older sessions may no longer work.\n"
        + "2. Press Play, then Multiplayer > Join Game > Direct Link. Use PASTE LINK for a copied invite, "
        + "or ENTER LINK to enter it with the in-game keyboard.\n"
        + "3. Wait for the host to appear, select it and JOIN GAME. If a lobby preview opens, choose JOIN GAME there. "
        + "Direct Link uses a native-port invite, not a retail Halo PC server address.\n\n"
        + "Sharing a host invite: Internet hosting copies it when available; selecting INVITE LINK in Server Setup "
        + "copies it again. A LAN game has no Internet invite. Treat private links as access to your game.\n\n"
        + "PASSWORDS\n"
        + "A lock in Server Browser means a password is required there. Select the game, enter the password, "
        + "then JOIN GAME; a wrong password can be corrected. A direct invite already grants access "
        + "and does not ask for the listing password.\n\n"
        + "SAVED INVITES FROM OLDER LAUNCHERS\n"
        + "Open Saved invites in this guide to view or copy your previous saved entries. They are retained locally; "
        + "nothing is uploaded or deleted. Old custom-directory preferences are also retained, but are not "
        + "automatically imported into the in-game browser.\n\n"
        + "Opening a supported invite link from another app still starts Halo. "
        + "Automatic clipboard invite detection is controlled by Settings > Network Setup > JOIN FROM CLIPBOARD "
        + "or the launcher Network settings. PASTE LINK is available for an explicit join.";

    static final String COMPATIBILITY =
        "NETWORK AND GAME FILES\n"
        + "This build hosts on OpenCE network 24. Launcher client targets cover 11–24, with 24 selected by default. "
        + "Use matching native-port networking versions on Quest, Android and compatible desktop ports. "
        + "The launcher directory can display listings from other network versions and their reported populations, "
        + "and lets you target one supported host version or all compatible versions on the next launch. "
        + "Legacy targets 11–22 support original Xbox-map PvP only; campaign and Custom Edition require 23 or 24. "
        + "Retail Halo PC/Custom Edition executables, Xbox and MCC do not share this protocol. "
        + "A directory can show incompatible, full or unreachable games; visibility alone does not establish compatibility.\n\n"
        + "Some server incompatibilities may be caused by different ISO/revision versions or modified game files. "
        + "Before launching, Game files & versions lets you import/select a supported game set. "
        + "Game data & compatibility reads its map headers and can fingerprint files for comparison. "
        + "A familiar map name or revision label is not proof of identical files. The browser cannot automatically "
        + "infer an Original/Rev1/Rev2 requirement. Use compatible mission/resource files for co-op.\n\n"
        + "CONNECTION TROUBLE\n"
        + "Check FILTERS and REFRESH if a game is missing. Make sure INTERNET PLAY is on for remote sessions. "
        + "If a host is visible but joining times out, try LAN or normal Wi-Fi without a VPN, "
        + "check firewall/router settings, and use the host's current invite. UPnP can help on supported routers; "
        + "carrier NAT or restrictive VPNs can still block peer connections. This port has no relay. "
        + "The launcher's Network settings retains an optional fixed UDP port for manual forwarding.\n\n"
        + "UPDATES AND REPORTS\n"
        + "Use launcher > Versions & updates for validated port updates; do not replace networking files "
        + "with arbitrary upstream binaries. If a newer protocol needs port changes, wait for a compatible build. "
        + "For crashes, desync or connection problems, send logs from both peers if possible, app/network versions, "
        + "device models, mission/map and game-set details, host/join roles, connection type, and reproduction steps. "
        + "Logs are in Download/HaloCE (newest halo_log_<date>_<time>.txt). "
        + "Report in https://discord.gg/S9uSCKxKx or DM @MeWhenINameMyself in the Flat2VR community.";
}
